export const categories = [
  'All',
  'Crystals & Gemstones',
  'Rudraksha',
  'Yantras',
  'Books & Scriptures',
  'Puja Items',
]

export const products = [
  // Crystals & Gemstones
  {
    id: 1,
    name: 'Amethyst Crystal Cluster',
    description: 'Natural amethyst for peace, meditation and spiritual clarity. Calms the mind and enhances intuition.',
    category: 'Crystals & Gemstones',
    price: '₹1,299',
    image: 'https://images.unsplash.com/photo-FwDuF0KHRrc?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 2,
    name: 'Clear Quartz Crystal',
    description: 'The master healer. Amplifies energy, intention and the effect of other crystals.',
    category: 'Crystals & Gemstones',
    price: '₹999',
    image: 'https://images.unsplash.com/photo-ymQlshzTVv0?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 3,
    name: 'Rose Quartz Palm Stone',
    description: 'Stone of unconditional love. Brings harmony, compassion and emotional healing.',
    category: 'Crystals & Gemstones',
    price: '₹749',
    image: 'https://images.unsplash.com/photo-SSoCY-Xi3iY?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 4,
    name: 'Black Tourmaline',
    description: 'Powerful protection stone. Shields against negative energy and electromagnetic radiation.',
    category: 'Crystals & Gemstones',
    price: '₹899',
    image: 'https://images.unsplash.com/photo-9R2hJWMMByY?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },

  // Rudraksha
  {
    id: 5,
    name: '5 Mukhi Rudraksha',
    description: 'Most auspicious and common bead. Represents Lord Shiva, promotes health, peace and spiritual growth.',
    category: 'Rudraksha',
    price: '₹599',
    image: 'https://images.unsplash.com/photo-kWy9W9rPRJ0?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 6,
    name: '1 Mukhi Rudraksha',
    description: 'Extremely rare and powerful. Represents pure consciousness, ideal for deep meditation and liberation.',
    category: 'Rudraksha',
    price: '₹4,999',
    image: 'https://images.unsplash.com/photo-S_HfQaz9Peo?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 7,
    name: '14 Mukhi Rudraksha',
    description: 'Awakens the third eye. Sharpens intuition, decision-making and opens the Ajna chakra.',
    category: 'Rudraksha',
    price: '₹2,499',
    image: 'https://images.unsplash.com/photo-MRHavETWyv4?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },

  // Yantras
  {
    id: 8,
    name: 'Shri Yantra (Copper)',
    description: 'Sacred geometry of the Goddess Lakshmi. Attracts wealth, abundance and cosmic harmony.',
    category: 'Yantras',
    price: '₹1,499',
    image: 'https://images.unsplash.com/photo-GsRaiFdcTY4?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 9,
    name: 'Vastu Yantra',
    description: 'Corrects Vastu doshas and brings positive energy, prosperity and peace to your home.',
    category: 'Yantras',
    price: '₹1,199',
    image: 'https://images.unsplash.com/photo-pGoITI0Xo7Q?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 10,
    name: 'Navgraha Yantra',
    description: 'Balances the influence of all nine planets. Reduces malefic effects and strengthens benefic ones.',
    category: 'Yantras',
    price: '₹1,799',
    image: 'https://images.unsplash.com/photo-EZ8Y4L8LumE?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },

  // Books & Scriptures
  {
    id: 11,
    name: 'Brihat Parasara Hora Shastra',
    description: 'The foundational text of Vedic astrology. An essential reference for students and practitioners.',
    category: 'Books & Scriptures',
    price: '₹849',
    image: 'https://images.unsplash.com/photo-6hOlSAQ-L98?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 12,
    name: 'Vastu Shastra — Ancient Wisdom',
    description: 'A comprehensive guide to Vedic architecture and spatial harmony for modern homes.',
    category: 'Books & Scriptures',
    price: '₹699',
    image: 'https://images.unsplash.com/photo-9T346Ij4kGk?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },

  // Puja Items
  {
    id: 13,
    name: 'Copper Puja Thali Set',
    description: 'Complete handcrafted copper thali set for daily rituals and worship ceremonies.',
    category: 'Puja Items',
    price: '₹1,099',
    image: 'https://images.unsplash.com/photo-C0mwgZ7XafU?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 14,
    name: 'Natural Dhoop Incense Sticks',
    description: 'Pure cow-dung and herb-based dhoop sticks for purifying spaces and creating sacred atmosphere.',
    category: 'Puja Items',
    price: '₹299',
    image: 'https://images.unsplash.com/photo-_12PwFpWZZ0?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
  {
    id: 15,
    name: 'Brass Diya Set (Pack of 6)',
    description: 'Traditional brass oil lamps, handcrafted for puja, festivals and meditation practice.',
    category: 'Puja Items',
    price: '₹549',
    image: 'https://images.unsplash.com/photo-zNY2lVIRh7M?w=400&h=400&fit=crop',
    amazonUrl: 'https://www.amazon.in',
  },
]
